-- indicators
--
-- One row per measure - 247, matching `measures` exactly, not one row per
-- language. The numeric indicators are language-independent; the copied
-- classification labels carry `_en` / `_fr` suffixes. `join_method` is carried
-- through so that the 36 measures that could not be paired across the two
-- editions stay visible in every query made over this view.
--
-- Every column is computed here from the Phase 0 and Phase 1 tables and from the
-- Phase 2 extraction tables. Nothing is stored, nothing is imputed, and a null
-- input produces a null output rather than a zero.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW indicators AS
WITH base AS (
    SELECT
        m.id                AS measure_id,
        b.cost_lang, b.cost_basis, b.cost_row_label,
        b.reference_lang, b.text_lang,

        (SELECT c.value_millions FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_estimate,
        (SELECT c.year FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_estimate_year,
        (SELECT c.raw_value FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_estimate_raw,
        (SELECT c.value_millions FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year ASC LIMIT 1)                  AS first_estimate,
        (SELECT c.year FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year ASC LIMIT 1)                  AS first_estimate_year,
        (SELECT c.raw_value FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'estimate'
          ORDER BY c.year ASC LIMIT 1)                  AS first_estimate_raw,
        (SELECT c.value_millions FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'projection'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_projection,
        (SELECT c.year FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'projection'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_projection_year,
        (SELECT c.raw_value FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.row_label = b.cost_row_label AND c.value_kind = 'projection'
          ORDER BY c.year DESC LIMIT 1)                 AS latest_projection_raw,

        (SELECT COUNT(DISTINCT c.year) FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang) AS years_published,
        (SELECT COUNT(DISTINCT c.year) FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.value_kind IN ('estimate','projection'))    AS years_numeric,
        (SELECT COUNT(DISTINCT c.year) FROM measure_costs c
          WHERE c.measure_id = m.id AND c.lang = b.cost_lang
            AND c.value_kind = 'withheld_confidential')       AS withheld_years,

        (SELECT bc.count FROM measure_beneficiary_counts bc
          WHERE bc.measure_id = m.id AND bc.method = 'pattern'
          ORDER BY bc.year DESC LIMIT 1)                AS beneficiaries_latest,
        (SELECT bc.year FROM measure_beneficiary_counts bc
          WHERE bc.measure_id = m.id AND bc.method = 'pattern'
          ORDER BY bc.year DESC LIMIT 1)                AS beneficiaries_latest_year,

        (SELECT MIN(h.year) FROM measure_history h
          WHERE h.measure_id = m.id AND h.year IS NOT NULL)   AS introduced_year,
        (SELECT MAX(h.year) FROM measure_history h
          WHERE h.measure_id = m.id AND h.year IS NOT NULL)   AS last_change_year,
        (SELECT COUNT(*) FROM measure_history h
          WHERE h.measure_id = m.id)                          AS history_events,

        (SELECT os.year FROM measure_objective_source os
          WHERE os.measure_id = m.id AND os.lang = b.text_lang) AS objective_source_year,
        (SELECT os.raw_text FROM measure_objective_source os
          WHERE os.measure_id = m.id AND os.lang = b.text_lang) AS objective_source_raw,
        (SELECT os.method FROM measure_objective_source os
          WHERE os.measure_id = m.id AND os.lang = b.text_lang) AS objective_source_method,

        (SELECT COUNT(*) FROM measure_objective_categories oc
          WHERE oc.measure_id = m.id AND oc.lang = b.text_lang) AS objective_categories,
        (SELECT COUNT(*) FROM measure_objective_categories oc
          WHERE oc.measure_id = m.id AND oc.lang = b.text_lang
            AND oc.group_name = 'internal')                    AS objective_categories_internal,

        (SELECT COUNT(*) FROM measure_references r
          WHERE r.measure_id = m.id AND r.lang = b.reference_lang) AS provisions_cited,
        (SELECT COUNT(*) FROM measure_references r
          WHERE r.measure_id = m.id AND r.lang = b.reference_lang
            AND r.status = 'resolved')                             AS provisions_resolved,
        (SELECT COUNT(*) FROM measure_references r
          WHERE r.measure_id = m.id AND r.lang = b.reference_lang
            AND r.status = 'not_in_consolidation')                 AS provisions_not_in_consolidation,
        (SELECT COUNT(DISTINCT p.act || ' ' || p.top_section)
           FROM measure_resolved_provisions p
          WHERE p.measure_id = m.id)                               AS sections_touched,
        (SELECT COUNT(DISTINCT o.other_measure_id)
           FROM measure_provision_overlap o
          WHERE o.measure_id = m.id)                               AS shared_with_measures,
        (SELECT SUM(aa.amending_entries) FROM (
            SELECT DISTINCT p.act, p.top_section
              FROM measure_resolved_provisions p
             WHERE p.measure_id = m.id) cited
          JOIN sections t ON t.act = cited.act
                         AND t.citation_path = cited.top_section
                         AND t.level = 'section'
          JOIN section_amending_acts aa ON aa.section_id = t.id)   AS amending_acts_count,

        (SELECT MIN(COALESCE(t.bound_date, PRINTF('%04d', t.bound_year)))
           FROM provision_temporal_scope t
           JOIN measure_resolved_provisions p ON p.section_id = t.section_id
          WHERE p.measure_id = m.id AND t.bound_kind = 'end')      AS earliest_end_date,
        (SELECT MAX(COALESCE(t.bound_date, PRINTF('%04d', t.bound_year)))
           FROM provision_temporal_scope t
           JOIN measure_resolved_provisions p ON p.section_id = t.section_id
          WHERE p.measure_id = m.id AND t.bound_kind = 'end')      AS latest_end_date,
        (SELECT COUNT(*)
           FROM provision_temporal_scope t
           JOIN measure_resolved_provisions p ON p.section_id = t.section_id
          WHERE p.measure_id = m.id)                               AS temporal_rows,
        (SELECT COUNT(*)
           FROM provision_temporal_scope t
           JOIN measure_resolved_provisions p ON p.section_id = t.section_id
          WHERE p.measure_id = m.id AND t.bound_kind = 'step_down') AS step_down_rows
    FROM measures m
    JOIN measure_figure_basis b ON b.measure_id = m.id
)
SELECT
    m.id                            AS measure_id,
    m.join_method,
    m.name_en,
    m.name_fr,

    b.cost_basis                    AS cost_figure_basis,
    b.cost_row_label                AS cost_figure_row_label,
    b.cost_lang                     AS cost_edition,
    b.latest_estimate               AS cost_latest_estimate,
    b.latest_estimate_year          AS cost_latest_estimate_year,
    b.latest_estimate_raw           AS cost_latest_estimate_raw,
    b.latest_projection             AS cost_latest_projection,
    b.latest_projection_year        AS cost_latest_projection_year,
    b.latest_projection_raw         AS cost_latest_projection_raw,
    b.first_estimate                AS cost_first_estimate,
    b.first_estimate_year           AS cost_first_estimate_year,
    b.first_estimate_raw            AS cost_first_estimate_raw,
    CASE WHEN b.latest_estimate IS NOT NULL
          AND b.first_estimate  IS NOT NULL
          AND b.latest_estimate_year <> b.first_estimate_year
         THEN b.latest_estimate - b.first_estimate END       AS cost_change_abs,
    CASE WHEN b.latest_estimate IS NOT NULL
          AND b.first_estimate  IS NOT NULL
          AND b.latest_estimate_year <> b.first_estimate_year
          AND b.first_estimate <> 0
         THEN (b.latest_estimate - b.first_estimate) / b.first_estimate END
                                                             AS cost_change_pct,
    CASE WHEN b.years_published = 0          THEN 'no_cost_table'
         WHEN b.withheld_years  > 0          THEN 'withheld'
         WHEN b.years_numeric   = 0          THEN 'not_costed'
         WHEN b.years_numeric   = b.years_published THEN 'costed'
         ELSE 'partially_costed' END                         AS cost_status,
    b.withheld_years                AS cost_withheld_years,

    b.beneficiaries_latest,
    b.beneficiaries_latest_year,
    m.number_of_beneficiaries_en    AS beneficiaries_raw_en,
    m.number_of_beneficiaries_fr    AS beneficiaries_raw_fr,
    CASE WHEN b.latest_estimate IS NOT NULL
          AND b.beneficiaries_latest IS NOT NULL
          AND b.beneficiaries_latest <> 0
          AND b.latest_estimate_year = b.beneficiaries_latest_year
         THEN b.latest_estimate * 1000000.0 / b.beneficiaries_latest END
                                                             AS cost_per_beneficiary,
    CASE WHEN b.latest_estimate IS NOT NULL
          AND b.beneficiaries_latest IS NOT NULL
          AND b.latest_estimate_year <> b.beneficiaries_latest_year
         THEN 'years_differ' END                             AS cost_per_beneficiary_note,

    b.introduced_year,
    b.last_change_year,
    CASE WHEN b.last_change_year IS NOT NULL
         THEN m.report_year - b.last_change_year END         AS years_since_last_change,
    b.history_events,

    b.objective_source_year,
    b.objective_source_raw,
    b.objective_source_method,

    m.category_en, m.category_fr,
    m.objective_category_en, m.objective_category_fr,
    m.subject_en, m.subject_fr,
    m.ccofog_2014_code_en AS ccofog_code_en,
    m.ccofog_2014_code_fr AS ccofog_code_fr,
    m.tax_en AS type_of_tax_en, m.tax_fr AS type_of_tax_fr,
    m.type_of_measure_en, m.type_of_measure_fr,
    CASE WHEN b.objective_categories = 0 THEN NULL
         WHEN b.objective_categories_internal = b.objective_categories THEN 1
         ELSE 0 END                                          AS objective_category_internal,
    CASE WHEN b.objective_categories = 0 THEN NULL
         WHEN b.objective_categories_internal > 0
          AND b.objective_categories_internal < b.objective_categories THEN 1
         ELSE 0 END                                          AS objective_category_mixed,
    CASE WHEN COALESCE(m.other_relevant_government_programs_en,
                       m.other_relevant_government_programs_fr) IS NULL THEN NULL
         WHEN TRIM(LOWER(COALESCE(m.other_relevant_government_programs_en,
                                  m.other_relevant_government_programs_fr)))
              IN ('n/a','s.o.','s. o.','n.a.') THEN 0
         ELSE 1 END                                          AS has_overlapping_program,
    m.other_relevant_government_programs_en AS overlapping_program_raw_en,
    m.other_relevant_government_programs_fr AS overlapping_program_raw_fr,

    b.provisions_cited,
    b.provisions_resolved,
    b.provisions_not_in_consolidation,
    b.sections_touched,
    b.shared_with_measures,
    b.amending_acts_count,
    CASE WHEN b.amending_acts_count IS NOT NULL THEN 'pattern' END
                                                             AS amending_acts_method,

    b.earliest_end_date,
    b.latest_end_date,
    CASE WHEN b.temporal_rows = 0 THEN NULL
         WHEN b.step_down_rows > 0 THEN 1 ELSE 0 END         AS has_step_down
FROM measures m
JOIN base b ON b.measure_id = m.id;
