-- measure_provision_overlap
--
-- One row per pair of measures that cite the same resolved provision, with the
-- provision. A pure join: no threshold, no score, and no statement that sharing a
-- provision means anything. Each unordered pair appears once in each direction,
-- so that a query filtered to one measure sees all of its partners.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW measure_provision_overlap AS
SELECT  a.measure_id   AS measure_id,
        b2.measure_id  AS other_measure_id,
        a.act,
        a.citation_path
FROM measure_resolved_provisions a
JOIN measure_resolved_provisions b2
     ON b2.act = a.act
    AND b2.citation_path = a.citation_path
    AND b2.measure_id <> a.measure_id
GROUP BY a.measure_id, b2.measure_id, a.act, a.citation_path;
