-- measure_resolved_provisions
--
-- Every resolved provision a measure cites, one row per reference, with the
-- top-level section it sits in. This is the join the legal-footprint indicators
-- and four of the canned views are built on, kept in one place so that the rule
-- for reading a section number out of a citation path is written once. Only the
-- edition named in `measure_figure_basis.reference_lang` is read, so a measure
-- present in both languages is not counted twice.
--
-- Includes `resolved_combined_stub` references. Those cite a subsection that
-- Justice Laws repealed inside a node covering several - "118.6(2) and (2.1)" -
-- and **`citation_path` here is that node's path, not the one Finance wrote**.
-- The measure's footprint does include it: Finance cites it and it locates a
-- real row in the Act. What it cannot do is stand for the cited path, which is
-- why the status is separate and why the reference table keeps Finance's
-- wording.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW measure_resolved_provisions AS
SELECT  r.measure_id,
        r.lang,
        r.order_index,
        s.act,
        s.id            AS section_id,
        s.citation_path,
        SUBSTR(s.citation_path, 1, MIN(
            CASE WHEN INSTR(s.citation_path,'(')>0 THEN INSTR(s.citation_path,'(')-1 ELSE LENGTH(s.citation_path) END,
            CASE WHEN INSTR(s.citation_path,'"')>0 THEN INSTR(s.citation_path,'"')-1 ELSE LENGTH(s.citation_path) END,
            CASE WHEN INSTR(s.citation_path,'~')>0 THEN INSTR(s.citation_path,'~')-1 ELSE LENGTH(s.citation_path) END))              AS top_section
FROM measure_references r
JOIN measure_figure_basis b
     ON b.measure_id = r.measure_id AND b.reference_lang = r.lang
JOIN sections s ON s.id = r.section_id
WHERE r.status IN ('resolved', 'resolved_combined_stub');
