-- v_end_bound_by_year
--
-- One row per extracted end bound on a provision a measure cites, with the
-- year as a column. The view is not filtered to any year: SQLite views take no
-- parameters, and a view named for a threshold would make the choice of
-- threshold look like a finding. The reader supplies it -
-- `WHERE end_year < 2027`. Whether a bound has passed is not computed here.
--
-- Empty until Phase 2 step 3 fills `provision_temporal_scope`.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_end_bound_by_year AS
SELECT p.measure_id,
       m.name_en, m.name_fr,
       p.act,
       p.citation_path AS cited_citation_path,
       s.citation_path AS provision_citation_path,
       t.phrase,
       t.bound_kind,
       t.bound_date,
       t.bound_precision,
       COALESCE(t.bound_year, CAST(SUBSTR(t.bound_date,1,4) AS INTEGER)) AS end_year,
       t.method
FROM provision_temporal_scope t
JOIN sections s ON s.id = t.section_id
JOIN measure_resolved_provisions p ON p.section_id = t.cited_section_id
JOIN measures m ON m.id = p.measure_id
WHERE t.bound_kind = 'end';
