-- v_last_change_by_year
--
-- One row per measure with the latest year Finance lists in its implementation
-- and recent history field, as a column for the reader to filter on. A null year
-- means no history event carried a year a pattern could read, which is not the
-- same as no change.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_last_change_by_year AS
SELECT measure_id, name_en, name_fr, join_method,
       introduced_year, last_change_year, years_since_last_change,
       history_events
FROM indicators;
