-- v_not_in_consolidation
--
-- Measures citing a provision the consolidation does not contain, with the
-- reference as published. This is the as-of-date gap - the report states the law
-- as at 31 December 2025 and the consolidation is dated 18 June 2026 - and it is
-- not an error by Finance or by Justice Canada.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_not_in_consolidation AS
SELECT r.measure_id,
       m.name_en, m.name_fr,
       r.raw_text,
       r.instrument,
       r.citation_path,
       r.lang,
       r.reason
FROM measure_references r
JOIN measure_figure_basis b
     ON b.measure_id = r.measure_id AND b.reference_lang = r.lang
JOIN measures m ON m.id = r.measure_id
WHERE r.status = 'not_in_consolidation';
