-- v_not_costed
--
-- Measures where Finance published a cost table and no year in it carries a
-- number. This is a measurement result, not a publishing decision: measures with
-- no cost table at all are `no_cost_table` and are not here. The view says
-- nothing about whether a measure should be costed.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_not_costed AS
SELECT measure_id, name_en, name_fr, join_method, cost_figure_basis,
       cost_status, provisions_cited, provisions_resolved
FROM indicators
WHERE cost_status = 'not_costed';
