-- v_no_beneficiary_count
--
-- Measures with no parsed beneficiary count, with the published sentence in
-- both languages. Mostly this is a statement about the prose of Finance's
-- "number of beneficiaries" field rather than about the measure: only 75 of the
-- published sentences carry a single number-and-year pair that a pattern can
-- read, and all 75 are in the English edition.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_no_beneficiary_count AS
SELECT measure_id, name_en, name_fr, join_method,
       beneficiaries_raw_en, beneficiaries_raw_fr
FROM indicators
WHERE beneficiaries_latest IS NULL;
