-- v_objective_internal
--
-- Measures every one of whose objective categories Finance's Part 3 lists
-- under "Objectives that are internal to the tax system". Finance's grouping,
-- read from each edition's own markup and shipped as a fixture. Measures carrying
-- both internal and other categories are excluded here and are marked
-- `objective_category_mixed` in `indicators`.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_objective_internal AS
SELECT measure_id, name_en, name_fr, join_method,
       objective_category_en, objective_category_fr,
       category_en, category_fr, cost_status
FROM indicators
WHERE objective_category_internal = 1;
