-- v_overlapping_programs
--
-- Measures where Finance's "other relevant government programs" field names
-- something. This is Finance's statement that related spending exists and nothing
-- more: it is not a duplication finding, and the field text travels with the flag
-- so a reader can see what was actually said.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_overlapping_programs AS
SELECT measure_id, name_en, name_fr, join_method,
       overlapping_program_raw_en, overlapping_program_raw_fr
FROM indicators
WHERE has_overlapping_program = 1;
