-- v_provision_footprint
--
-- For every resolved provision: the measure citing it, and the number of other
-- measures that cite the same provision or another provision of the same section.
-- One row per (provision, measure) pair, which is the longer shape and the useful
-- one - a reader asking about a single provision filters
-- `WHERE citation_path = '20(1)(ss)'` and sees each measure on its own row.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_provision_footprint AS
SELECT p.act,
       p.citation_path,
       p.top_section,
       p.measure_id,
       m.name_en,
       m.name_fr,
       (SELECT COUNT(DISTINCT q.measure_id) FROM measure_resolved_provisions q
         WHERE q.act = p.act AND q.citation_path = p.citation_path
           AND q.measure_id <> p.measure_id)            AS other_measures_citing_provision,
       (SELECT COUNT(DISTINCT q.measure_id) FROM measure_resolved_provisions q
         WHERE q.act = p.act AND q.top_section = p.top_section
           AND q.measure_id <> p.measure_id)            AS other_measures_in_section
FROM measure_resolved_provisions p
JOIN measures m ON m.id = p.measure_id
GROUP BY p.act, p.citation_path, p.measure_id;
