-- v_shared_provisions
--
-- Resolved provisions cited by more than one `measures` row, with the rows.
--
-- **The count is of rows, not of measures, and the two differ.** `measures`
-- holds 211 joined pairs and 36 unjoined singles, and an English single and its
-- French counterpart are two rows describing one measure. A path cited by both
-- therefore reports 2 where the honest answer is 1 - the Accelerated Investment
-- Incentive, rows 205 and 237, is the clearest case.
--
-- `unjoined_singles_citing` says how much of the count could be that, so the
-- inflation is visible in the view rather than needing to be known about.
--
-- **It is not collapsed, and the attempt is why.** Collapsing on the resolved
-- provision set merges "Expensing of advertising costs" with "Expensing of
-- employee training costs", which cite the same provision and are different
-- measures. Adding cost values - Phase 1's full join signature - separates
-- those two but then fails to pair the donation measures, whose editions parsed
-- 88 and 48 cost rows from the same tables. Restricting to unique
-- one-English-one-French groups collapses nothing at all. There is no mechanical
-- key that pairs the singles that should pair without merging the ones that
-- should not, which is exactly why Phase 1 left them as singles. Encoding a
-- guess here would put a judgment in a view whose whole claim is that it makes
-- none.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_shared_provisions AS
SELECT p.act,
       p.citation_path,
       COUNT(DISTINCT p.measure_id)                    AS measure_rows_citing,
       SUM(CASE WHEN m.join_method IS NULL THEN 1 ELSE 0 END)
                                                       AS unjoined_singles_citing,
       GROUP_CONCAT(DISTINCT p.measure_id)             AS measure_ids
FROM measure_resolved_provisions p
JOIN measures m ON m.id = p.measure_id
GROUP BY p.act, p.citation_path
HAVING COUNT(DISTINCT p.measure_id) > 1;
