-- v_shared_provisions
--
-- Resolved provisions cited by more than one measure, with the measures. A
-- provision appearing here is one Finance's report reaches from several
-- directions; the view counts the measures and lists them, and draws no
-- conclusion from the count.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_shared_provisions AS
SELECT p.act,
       p.citation_path,
       COUNT(DISTINCT p.measure_id) AS measures_citing,
       GROUP_CONCAT(DISTINCT p.measure_id) AS measure_ids
FROM measure_resolved_provisions p
GROUP BY p.act, p.citation_path
HAVING COUNT(DISTINCT p.measure_id) > 1;
