-- v_withheld
--
-- Measures with at least one cost cell published as "X", which Finance's own
-- legend defines as withheld for confidentiality. A withheld cell is not an
-- absence of data and is never a zero; the count of years affected is given so a
-- reader can see how much of the series is missing by Finance's choice.
--
-- Generated by portage/indicators.py. Do not edit.

CREATE VIEW v_withheld AS
SELECT measure_id, name_en, name_fr, join_method,
       cost_withheld_years, cost_status, cost_figure_basis
FROM indicators
WHERE cost_withheld_years > 0;
